export { default as Home } from './Home'
export { default as LogIn } from './LogIn'
export { default as SingUp } from './SingUp'
export { default as Surveys } from './Surveys'
export { default as ViewSurveys } from './ViewSurveys'
export { default as Footer } from '../molecules/Footer'
export { default as Pagina404 } from './Pagina404'
export { default as Profile } from './Profile'