export { default as Home } from './Home'
export { default as LogIn } from './LogIn'
export { default as SingUp } from './SingUp'
export { default as Surveys } from './Surveys'
export { default as ViewSurveys } from './ViewSurveys'
export { default as Footer } from '../Footer'
export { default as Error } from '../molecules/Error'
export { default as Profile } from './Profile'