export { default as Nav } from './Nav'
export { default as SideImage } from './SideImage'
export { default as CardSurvey } from './CardSurvey'
export { default as Pagina404 } from '../pages/Pagina404'
export { default as Modal } from './ModalLogIn'